---
- hosts: myWebservers
  become: yes
  tasks: 
  - name: install java on ubuntu 
    apt:
      name: "{{myjavapackonubntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on RedHat
    dnf:
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"