---
- hosts: 172.31.18.192
  become: yes
  vars: 
    var01: git
    var02: tree
    var03: wget
  tasks:
  - name: i want to display var01 
    apt:
      name: "{{var01}}"
      state: present 
      
  - name: i want to execute direct linux command
    command: hostname -f
    register: myresult
  
  - name: i want to display above task result 
    debug: 
        msg: "{{myresult}}"

  - name:  install git 
    apt: 
      name: git 
      state: present
    when: myresult.stderr !=""

  - name: install wget 
    apt:
      name: wget
      state: present
    when: myresult.stderr ==""


  
         
  