---
- hosts: 172.31.18.192
  become: yes
  vars: 
    var01: git
    var02: tree
    var03: wget
  tasks:
  - name: i want to display var01 
    apt:
      name: "{{var01}}"
      state: present 
  - name: i want to execute direct linux command
    command: hostsname -f
  
  
         
  