---
- name: create group
  group:
     name: tomcat 
     state: present 

- name: Create user 
  user: 
     name: user 
     shell: /bin/false
     group: tomcat
     home: /opt/tomcat 
     state: present




